FROM python:3.11-bookworm
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    iputils-ping \
    netcat-openbsd \
    dnsutils \
    gcc python3-dev && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install requests beautifulsoup4 kafka-python

ENV PYTHONUNBUFFERED=1

CMD ["python", "reddit_scraper.py", "-v"]
